name: Java CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: 
          cd my-java-app
          mvn clean install

      - name: Run Tests
        run: |
            cd my-java-app
            mvn clean install

      - name: OWASP Dependency Check
        run: mvn org.owasp:dependency-check-maven:check

      - name: Build Docker Image
        run: docker build -t myrepo/my-java-app:${{ github.sha }} .

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'myrepo/my-java-app:${{ github.sha }}'
          severity: 'CRITICAL,HIGH'

